package com.example.cachelib;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //检查更新信息
        CoreApi coreApi = new CoreApi();
        coreApi.startCheck();
    }
}
